package id.co.bni.calculator.models;
/**
 * CalculatorRequest
 * ============================================================================
 * TUJUAN:
 *   Model request untuk operasi kalkulator. Menerima dua angka (a dan b) sebagai input.
 *
 * Generated by: springboot-generator MCP v7.0
 */

public class CalculatorRequest {

    private double a;
    private double b;

    public CalculatorRequest() {}

    public CalculatorRequest(double a, double b) {
        this.a = a;
        this.b = b;
    }

    public double getA() { return a; }
    public void setA(double a) { this.a = a; }

    public double getB() { return b; }
    public void setB(double b) { this.b = b; }
}
