package id.co.bni.calculator;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * CalculatorApplication - Titik masuk (entry point) aplikasi Spring Boot calculator.
 * ============================================================================
 * TUJUAN:
 *   Bootstrap aplikasi Spring Boot dan menjalankan embedded Tomcat server.
 *   Class ini yang dijalankan pertama kali saat `mvn spring-boot:run` atau `java -jar`.
 *
 * ALUR STARTUP:
 *   1. SpringApplication.run() dipanggil dari main()
 *   2. Spring scan semua @Component, @Service, @Repository, @RestController
 *      di dalam package id.co.bni.calculator dan sub-package-nya
 *   3. Embedded Tomcat mulai listen di port yang diset di application.properties
 *   4. Aplikasi siap menerima request HTTP
 *
 * KONVENSI PACKAGE:
 *   - controllers/   → REST Controller (endpoint HTTP)
 *   - services/      → Business logic
 *   - repositories/  → Akses database (JPA)
 *   - models/        → Entity, DTO, ApiResponse, AppException
 *   - configs/       → Konfigurasi Spring (interceptor, filter, exception handler)
 *   - utils/         → Helper class (ResponseCodeHelper, ApiOrderContext)
 *
 * CARA MENJALANKAN:
 *   - Development : mvn spring-boot:run
 *   - Production  : java -jar target/calculator-0.0.1-SNAPSHOT.jar
 *   - Build JAR   : mvn clean package
 *
 * Generated by: springboot-generator MCP v7.0
 */
@SpringBootApplication
public class CalculatorApplication {

	public static void main(String[] args) {
		SpringApplication.run(CalculatorApplication.class, args);
	}

}
