jobs:
  ci:
    uses: muhammad0510/ci-templates/.github/workflows/springboot-ci.yml@main
    with:
      sonar-project-key: YasinMochamad_kalkulator
      sonar-organization: yasinmochamad
      newman-collection: collections/calculator_newman_chain_v3.json
      newman-environment: collections/calculator_newman_chain_env_v2.json
    secrets: inherit
